# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: push

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 16, 17, 21]
        dist: ['temurin', 'zulu', 'corretto']

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: ${{matrix.dist}}

    - name: Build with Maven
      run: mvn -B compile --file pom.xml assembly:single

    - name: Run test
      run: java -jar target/EzAAI-*.jar -nc -h